# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(880, 518)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.queue_list_widget = QtWidgets.QListWidget(self.centralwidget)
        self.queue_list_widget.setGeometry(QtCore.QRect(10, 60, 171, 401))
        self.queue_list_widget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.queue_list_widget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.queue_list_widget.setLineWidth(-1)
        self.queue_list_widget.setMidLineWidth(0)
        self.queue_list_widget.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.queue_list_widget.setProperty("isWrapping", True)
        self.queue_list_widget.setWordWrap(False)
        self.queue_list_widget.setObjectName("queue_list_widget")
        self.run_queue_button = QtWidgets.QPushButton(self.centralwidget)
        self.run_queue_button.setGeometry(QtCore.QRect(190, 310, 101, 41))
        self.run_queue_button.setObjectName("run_queue_button")
        self.logger_text = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.logger_text.setGeometry(QtCore.QRect(190, 360, 681, 131))
        self.logger_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.logger_text.setReadOnly(True)
        self.logger_text.setObjectName("logger_text")
        self.add_queue_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_queue_button.setGeometry(QtCore.QRect(190, 60, 101, 41))
        self.add_queue_button.setObjectName("add_queue_button")
        self.remove_queue_button = QtWidgets.QPushButton(self.centralwidget)
        self.remove_queue_button.setGeometry(QtCore.QRect(190, 160, 101, 41))
        self.remove_queue_button.setObjectName("remove_queue_button")
        self.edit_queue_button = QtWidgets.QPushButton(self.centralwidget)
        self.edit_queue_button.setGeometry(QtCore.QRect(190, 110, 101, 41))
        self.edit_queue_button.setObjectName("edit_queue_button")
        self.autoplay_button = QtWidgets.QPushButton(self.centralwidget)
        self.autoplay_button.setGeometry(QtCore.QRect(660, 310, 101, 41))
        self.autoplay_button.setObjectName("autoplay_button")
        self.daily_trivia_button = QtWidgets.QPushButton(self.centralwidget)
        self.daily_trivia_button.setGeometry(QtCore.QRect(770, 60, 101, 41))
        self.daily_trivia_button.setObjectName("daily_trivia_button")
        self.world_boss_invasion_button = QtWidgets.QPushButton(self.centralwidget)
        self.world_boss_invasion_button.setGeometry(QtCore.QRect(660, 110, 101, 41))
        self.world_boss_invasion_button.setCheckable(False)
        self.world_boss_invasion_button.setAutoRepeat(False)
        self.world_boss_invasion_button.setAutoExclusive(False)
        self.world_boss_invasion_button.setFlat(False)
        self.world_boss_invasion_button.setObjectName("world_boss_invasion_button")
        self.squad_battle_button = QtWidgets.QPushButton(self.centralwidget)
        self.squad_battle_button.setGeometry(QtCore.QRect(660, 60, 101, 41))
        self.squad_battle_button.setObjectName("squad_battle_button")
        self.screen_label = QtWidgets.QLabel(self.centralwidget)
        self.screen_label.setGeometry(QtCore.QRect(300, 60, 351, 197))
        self.screen_label.setAutoFillBackground(False)
        self.screen_label.setStyleSheet("background-color: rgb(254, 255, 176);\n"
"color: rgb(0, 0, 127);")
        self.screen_label.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.screen_label.setLineWidth(1)
        self.screen_label.setMidLineWidth(0)
        self.screen_label.setText("")
        self.screen_label.setObjectName("screen_label")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(310, 310, 171, 41))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.acquire_heroic_quest_rewards_checkbox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.acquire_heroic_quest_rewards_checkbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.acquire_heroic_quest_rewards_checkbox.setChecked(True)
        self.acquire_heroic_quest_rewards_checkbox.setObjectName("acquire_heroic_quest_rewards_checkbox")
        self.verticalLayout.addWidget(self.acquire_heroic_quest_rewards_checkbox)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(500, 290, 101, 31))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.mission_team_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.mission_team_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mission_team_label.setAutoFillBackground(False)
        self.mission_team_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mission_team_label.setObjectName("mission_team_label")
        self.verticalLayout_2.addWidget(self.mission_team_label)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(500, 320, 101, 31))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.timeline_team_label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.timeline_team_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.timeline_team_label.setObjectName("timeline_team_label")
        self.verticalLayout_3.addWidget(self.timeline_team_label)
        self.mission_team_spin_box = QtWidgets.QSpinBox(self.centralwidget)
        self.mission_team_spin_box.setGeometry(QtCore.QRect(610, 290, 31, 31))
        self.mission_team_spin_box.setMinimum(1)
        self.mission_team_spin_box.setMaximum(5)
        self.mission_team_spin_box.setObjectName("mission_team_spin_box")
        self.timeline_team_spin_box = QtWidgets.QSpinBox(self.centralwidget)
        self.timeline_team_spin_box.setGeometry(QtCore.QRect(610, 320, 31, 31))
        self.timeline_team_spin_box.setMinimum(1)
        self.timeline_team_spin_box.setMaximum(5)
        self.timeline_team_spin_box.setObjectName("timeline_team_spin_box")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 0, 861, 41))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(25)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_username = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_username.setAlignment(QtCore.Qt.AlignCenter)
        self.label_username.setObjectName("label_username")
        self.horizontalLayout_5.addWidget(self.label_username)
        self.label_energy = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_energy.setAlignment(QtCore.Qt.AlignCenter)
        self.label_energy.setObjectName("label_energy")
        self.horizontalLayout_5.addWidget(self.label_energy)
        self.label_gold = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_gold.setAlignment(QtCore.Qt.AlignCenter)
        self.label_gold.setObjectName("label_gold")
        self.horizontalLayout_5.addWidget(self.label_gold)
        self.label_boosts = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_boosts.setAutoFillBackground(False)
        self.label_boosts.setAlignment(QtCore.Qt.AlignCenter)
        self.label_boosts.setObjectName("label_boosts")
        self.horizontalLayout_5.addWidget(self.label_boosts)
        self.horizontalLayout_5.setStretch(0, 2)
        self.horizontalLayout_5.setStretch(1, 1)
        self.horizontalLayout_5.setStretch(2, 1)
        self.horizontalLayout_5.setStretch(3, 1)
        self.mission_queue_txt = QtWidgets.QLabel(self.centralwidget)
        self.mission_queue_txt.setGeometry(QtCore.QRect(16, 33, 71, 20))
        self.mission_queue_txt.setAutoFillBackground(True)
        self.mission_queue_txt.setAlignment(QtCore.Qt.AlignCenter)
        self.mission_queue_txt.setObjectName("mission_queue_txt")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 34, 881, 20))
        self.line.setStyleSheet("color: rgb(185, 185, 185);")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.game_screen_txt = QtWidgets.QLabel(self.centralwidget)
        self.game_screen_txt.setGeometry(QtCore.QRect(306, 33, 66, 20))
        self.game_screen_txt.setAutoFillBackground(True)
        self.game_screen_txt.setAlignment(QtCore.Qt.AlignCenter)
        self.game_screen_txt.setObjectName("game_screen_txt")
        self.quick_start_txt = QtWidgets.QLabel(self.centralwidget)
        self.quick_start_txt.setGeometry(QtCore.QRect(666, 33, 56, 20))
        self.quick_start_txt.setAutoFillBackground(True)
        self.quick_start_txt.setAlignment(QtCore.Qt.AlignCenter)
        self.quick_start_txt.setObjectName("quick_start_txt")
        self.settings_txt = QtWidgets.QLabel(self.centralwidget)
        self.settings_txt.setGeometry(QtCore.QRect(310, 270, 46, 20))
        self.settings_txt.setAutoFillBackground(True)
        self.settings_txt.setAlignment(QtCore.Qt.AlignCenter)
        self.settings_txt.setObjectName("settings_txt")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(304, 273, 347, 16))
        self.line_2.setStyleSheet("color: rgb(185, 185, 185);")
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(303, 282, 3, 81))
        self.line_3.setStyleSheet("color: rgb(185, 185, 185);")
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(649, 282, 3, 81))
        self.line_4.setStyleSheet("color: rgb(185, 185, 185);")
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setObjectName("line_4")
        self.list_select_all_button = QtWidgets.QPushButton(self.centralwidget)
        self.list_select_all_button.setGeometry(QtCore.QRect(10, 470, 75, 23))
        self.list_select_all_button.setObjectName("list_select_all_button")
        self.list_deselect_all_button = QtWidgets.QPushButton(self.centralwidget)
        self.list_deselect_all_button.setGeometry(QtCore.QRect(106, 470, 75, 23))
        self.list_deselect_all_button.setObjectName("list_deselect_all_button")
        self.shield_lab_button = QtWidgets.QPushButton(self.centralwidget)
        self.shield_lab_button.setGeometry(QtCore.QRect(770, 110, 101, 41))
        self.shield_lab_button.setObjectName("shield_lab_button")
        self.danger_room_button = QtWidgets.QPushButton(self.centralwidget)
        self.danger_room_button.setGeometry(QtCore.QRect(660, 160, 101, 41))
        self.danger_room_button.setObjectName("danger_room_button")
        self.restart_game_button = QtWidgets.QPushButton(self.centralwidget)
        self.restart_game_button.setGeometry(QtCore.QRect(770, 310, 101, 41))
        self.restart_game_button.setObjectName("restart_game_button")
        self.line_4.raise_()
        self.line_3.raise_()
        self.line_2.raise_()
        self.line.raise_()
        self.queue_list_widget.raise_()
        self.run_queue_button.raise_()
        self.logger_text.raise_()
        self.add_queue_button.raise_()
        self.remove_queue_button.raise_()
        self.edit_queue_button.raise_()
        self.autoplay_button.raise_()
        self.daily_trivia_button.raise_()
        self.world_boss_invasion_button.raise_()
        self.squad_battle_button.raise_()
        self.screen_label.raise_()
        self.verticalLayoutWidget.raise_()
        self.verticalLayoutWidget_2.raise_()
        self.verticalLayoutWidget_3.raise_()
        self.mission_team_spin_box.raise_()
        self.timeline_team_spin_box.raise_()
        self.horizontalLayoutWidget_5.raise_()
        self.mission_queue_txt.raise_()
        self.game_screen_txt.raise_()
        self.quick_start_txt.raise_()
        self.settings_txt.raise_()
        self.list_select_all_button.raise_()
        self.list_deselect_all_button.raise_()
        self.shield_lab_button.raise_()
        self.danger_room_button.raise_()
        self.restart_game_button.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 880, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.queue_list_widget.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MFF Auto"))
        self.queue_list_widget.setSortingEnabled(False)
        self.run_queue_button.setText(_translate("MainWindow", "Run"))
        self.add_queue_button.setText(_translate("MainWindow", "Add"))
        self.remove_queue_button.setText(_translate("MainWindow", "Remove"))
        self.edit_queue_button.setText(_translate("MainWindow", "Edit"))
        self.autoplay_button.setText(_translate("MainWindow", "Autoplay++"))
        self.daily_trivia_button.setText(_translate("MainWindow", "Daily Trivia"))
        self.world_boss_invasion_button.setText(_translate("MainWindow", "World Boss \n"
"Invasion: ALL"))
        self.squad_battle_button.setText(_translate("MainWindow", "Squad Battles: \n"
"ALL"))
        self.acquire_heroic_quest_rewards_checkbox.setText(_translate("MainWindow", "Acquire Heroic Quest rewards"))
        self.mission_team_label.setText(_translate("MainWindow", "Mission Team:"))
        self.timeline_team_label.setText(_translate("MainWindow", "Timeline Team:"))
        self.label_username.setText(_translate("MainWindow", "Username"))
        self.label_energy.setText(_translate("MainWindow", "Energy: 100/100"))
        self.label_gold.setText(_translate("MainWindow", "Gold: 123123312"))
        self.label_boosts.setText(_translate("MainWindow", "Boost: 100"))
        self.mission_queue_txt.setText(_translate("MainWindow", "Mission queue"))
        self.game_screen_txt.setText(_translate("MainWindow", "Game screen"))
        self.quick_start_txt.setText(_translate("MainWindow", "Quick start"))
        self.settings_txt.setText(_translate("MainWindow", "Settings"))
        self.list_select_all_button.setText(_translate("MainWindow", "Select All"))
        self.list_deselect_all_button.setText(_translate("MainWindow", "Deselect All"))
        self.shield_lab_button.setText(_translate("MainWindow", "Shield Lab:\n"
"Collect Antimatter"))
        self.danger_room_button.setText(_translate("MainWindow", "Danger Room:\n"
"One Battle"))
        self.restart_game_button.setText(_translate("MainWindow", "Restart Game"))
