# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'queue_editor_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(435, 338)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.select_mode_tool_button = QtWidgets.QToolButton(Dialog)
        self.select_mode_tool_button.setMinimumSize(QtCore.QSize(100, 40))
        self.select_mode_tool_button.setObjectName("select_mode_tool_button")
        self.horizontalLayout_2.addWidget(self.select_mode_tool_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_3.setObjectName("formLayout_3")
        self.all_stages_check_box = QtWidgets.QCheckBox(Dialog)
        self.all_stages_check_box.setChecked(True)
        self.all_stages_check_box.setObjectName("all_stages_check_box")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.all_stages_check_box)
        self.farm_bios_check_box = QtWidgets.QCheckBox(Dialog)
        self.farm_bios_check_box.setObjectName("farm_bios_check_box")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.farm_bios_check_box)
        self.zero_boosts_check_box = QtWidgets.QCheckBox(Dialog)
        self.zero_boosts_check_box.setObjectName("zero_boosts_check_box")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.zero_boosts_check_box)
        self.use_hidden_tickets_checkbox = QtWidgets.QCheckBox(Dialog)
        self.use_hidden_tickets_checkbox.setChecked(True)
        self.use_hidden_tickets_checkbox.setObjectName("use_hidden_tickets_checkbox")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.use_hidden_tickets_checkbox)
        self.dm_acquire_rewards_checkbox = QtWidgets.QCheckBox(Dialog)
        self.dm_acquire_rewards_checkbox.setChecked(True)
        self.dm_acquire_rewards_checkbox.setObjectName("dm_acquire_rewards_checkbox")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.dm_acquire_rewards_checkbox)
        self.timeline_skip_label = QtWidgets.QLabel(Dialog)
        self.timeline_skip_label.setObjectName("timeline_skip_label")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.timeline_skip_label)
        self.timeline_skip_combobox = QtWidgets.QSpinBox(Dialog)
        self.timeline_skip_combobox.setAlignment(QtCore.Qt.AlignCenter)
        self.timeline_skip_combobox.setMinimum(0)
        self.timeline_skip_combobox.setProperty("value", 0)
        self.timeline_skip_combobox.setObjectName("timeline_skip_combobox")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.timeline_skip_combobox)
        self.mission_mode_combo_box = QtWidgets.QComboBox(Dialog)
        self.mission_mode_combo_box.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mission_mode_combo_box.setObjectName("mission_mode_combo_box")
        self.mission_mode_combo_box.addItem("")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.mission_mode_combo_box)
        self.mission_mode_label = QtWidgets.QLabel(Dialog)
        self.mission_mode_label.setObjectName("mission_mode_label")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.mission_mode_label)
        self.legendary_battle_label = QtWidgets.QLabel(Dialog)
        self.legendary_battle_label.setObjectName("legendary_battle_label")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.legendary_battle_label)
        self.legendary_battle_combo_box = QtWidgets.QComboBox(Dialog)
        self.legendary_battle_combo_box.setObjectName("legendary_battle_combo_box")
        self.legendary_battle_combo_box.addItem("")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.legendary_battle_combo_box)
        self.legendary_battle_stage_label = QtWidgets.QLabel(Dialog)
        self.legendary_battle_stage_label.setObjectName("legendary_battle_stage_label")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.legendary_battle_stage_label)
        self.legendary_battle_stage_combo_box = QtWidgets.QComboBox(Dialog)
        self.legendary_battle_stage_combo_box.setObjectName("legendary_battle_stage_combo_box")
        self.legendary_battle_stage_combo_box.addItem("")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.legendary_battle_stage_combo_box)
        self.horizontalLayout.addLayout(self.formLayout_3)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.formLayout_2.setObjectName("formLayout_2")
        self.stages_label = QtWidgets.QLabel(Dialog)
        self.stages_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.stages_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.stages_label.setObjectName("stages_label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.stages_label)
        self.stages_spin_box = QtWidgets.QSpinBox(Dialog)
        self.stages_spin_box.setAlignment(QtCore.Qt.AlignCenter)
        self.stages_spin_box.setMinimum(1)
        self.stages_spin_box.setObjectName("stages_spin_box")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.stages_spin_box)
        self.difficulty_label = QtWidgets.QLabel(Dialog)
        self.difficulty_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.difficulty_label.setObjectName("difficulty_label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.difficulty_label)
        self.difficulty_spin_box = QtWidgets.QSpinBox(Dialog)
        self.difficulty_spin_box.setAlignment(QtCore.Qt.AlignCenter)
        self.difficulty_spin_box.setMinimum(1)
        self.difficulty_spin_box.setObjectName("difficulty_spin_box")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.difficulty_spin_box)
        self.horizontalLayout.addLayout(self.formLayout_2)
        self.horizontalLayout.setStretch(0, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.editor_button_box = QtWidgets.QDialogButtonBox(Dialog)
        self.editor_button_box.setOrientation(QtCore.Qt.Horizontal)
        self.editor_button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.editor_button_box.setObjectName("editor_button_box")
        self.verticalLayout.addWidget(self.editor_button_box)
        self.verticalLayout.setStretch(2, 1)

        self.retranslateUi(Dialog)
        self.mission_mode_combo_box.setCurrentIndex(0)
        self.editor_button_box.accepted.connect(Dialog.accept)
        self.editor_button_box.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add mission to queue"))
        self.select_mode_tool_button.setText(_translate("Dialog", "Select Mode"))
        self.all_stages_check_box.setText(_translate("Dialog", "All stages"))
        self.farm_bios_check_box.setText(_translate("Dialog", "Farm bios"))
        self.zero_boosts_check_box.setText(_translate("Dialog", "Stop when 0 boost points"))
        self.use_hidden_tickets_checkbox.setText(_translate("Dialog", "Use Hidden Tickets"))
        self.dm_acquire_rewards_checkbox.setText(_translate("Dialog", "Acquire rewards"))
        self.timeline_skip_label.setText(_translate("Dialog", "How many opponents to skip"))
        self.mission_mode_combo_box.setCurrentText(_translate("Dialog", "ULTIMATE TEST"))
        self.mission_mode_combo_box.setItemText(0, _translate("Dialog", "ULTIMATE TEST"))
        self.mission_mode_label.setText(_translate("Dialog", "Select mission mode:"))
        self.legendary_battle_label.setText(_translate("Dialog", "Select legendary battle"))
        self.legendary_battle_combo_box.setItemText(0, _translate("Dialog", "TEST LEGENDARY BATTLE"))
        self.legendary_battle_stage_label.setText(_translate("Dialog", "Select legendary battle stage"))
        self.legendary_battle_stage_combo_box.setItemText(0, _translate("Dialog", "TEST LEGENDARY STAGE"))
        self.stages_label.setText(_translate("Dialog", "Stages:"))
        self.difficulty_label.setText(_translate("Dialog", "Difficulty:"))
